a = 5;
console.log("Genaral variable declaration a = 'a':", a);
var b = 'v';
console.log("This variable belongs to var type(global) value b:", b);
b = 10;
console.log("This variable belongs to var type and updated b values is: ", b);
let c = 'let';
console.log("This variable belongs to let type and value c is:", c);
const d = 100;
console.log("Constant variable const d =", d);
d = 200;